apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "the-redemption.fullname" . }}
  labels:
    {{- include "the-redemption.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable | quote }}
  selector:
    matchLabels:
      {{- include "the-redemption.selectorLabels" . | nindent 6 }}
