apiVersion: v1
kind: Service
metadata:
  name: the-redemption
  namespace: the-redemption
  labels:
    {{- include "the-redemption.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: the-redemption
  ports:
    - name: http
      port: 80
      targetPort: http
